CONFIG_FILE="$HOME/.dropconfig"
CONFIG_DIR="$HOME/Dropbox/DropConfig/"

# Color Information
SUCCESS_TEXT_COLOR="\e[0;32m"
INFO_TEXT_COLOR="\e[0;33m"
ERROR_TEXT_COLOR="\e[0;31m"
PATH_TEXT_COLOR="\e[0;36m"
DEFAULT_TEXT_COLOR="\e[00m"
